dist: xenial
sudo: true
addons:
  chrome: stable
  apt:
    packages:
      - libsnappy-dev
      - libgconf-2-4
language: node_js
node_js: 8.16.0
env:
  global:
    - EQ_RUN_FUNCTIONAL_TESTS_HEADLESS=True
    - EQ_DYNAMODB_ENDPOINT=http://localhost:6060
    - EQ_SUBMITTED_RESPONSES_TABLE_NAME=dev-submitted-responses
    - EQ_QUESTIONNAIRE_STATE_TABLE_NAME=dev-questionnaire-state
    - EQ_SESSION_TABLE_NAME=dev-eq-session
    - EQ_USED_JTI_CLAIM_TABLE_NAME=dev-used-jti-claim
    - AWS_DEFAULT_REGION=eu-west-1
    - AWS_ACCESS_KEY_ID=dummy-access-key
    - AWS_SECRET_ACCESS_KEY=dummy-secret-key
    - PATH=$PATH:/opt/jsonnet
    - PYENV_VERSION=2.7.15
before_install:
    - export BOTO_CONFIG=/dev/null # Workaround for https://github.com/travis-ci/travis-ci/issues/7940
    - cd /opt/pyenv/plugins/python-build/../.. && git pull origin master && cd -
    - pyenv versions
    - pyenv install --skip-existing
    - pyenv rehash
    - pip install -U pip pipenv wheel
    - pipenv install --dev --deploy
    - pipenv check
cache:
    - yarn
    - pip
    - directories:
        - /opt/python/
        - /home/travis/.local/share/
script:
    - set -e
    - printf $(git rev-parse HEAD) > .application-version
    - make travis
    - export TAG=`if [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then echo "latest"; else echo branch-$(echo $TRAVIS_PULL_REQUEST_BRANCH | sed s:/:-:g); fi`
    - docker tag onsdigital/eq-questionnaire-runner:latest onsdigital/eq-questionnaire-runner:$TAG
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - echo "Pushing with tag [$TAG]"
    - docker push onsdigital/eq-questionnaire-runner:$TAG

after_success:
    - pyenv global $(cat .python-version)
    - pipenv run pip install codecov
    - pipenv run codecov
    - pipenv run pip install codacy-coverage
    - pipenv run python-codacy-coverage -r coverage.xml
branches:
    only:
        - master
