name: Schemas release PR

on:
  repository_dispatch:
    types: schemas_release

jobs:
  create-pull-request:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Update and commit schemas version
        run: |
          TAG="${{ github.event.client_payload.tag }}"
          echo "SCHEMAS_VERSION=$TAG" >> $GITHUB_ENV

          # Import GPG key to sign the commit
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --import --no-tty --batch --yes

          # Set Git GPG program and signing key
          git config --global gpg.program $(which gpg)
          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"

          # Update Git user details to match gpg key
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

          # Update and commit schemas version file
          echo $TAG > .schemas-version
          git add -A
          git commit -S -m "Update schemas version to $TAG"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: "${{ secrets.REPO_ACCESS_TOKEN }}"
          commit-message: "Update schemas to version ${{ env.SCHEMAS_VERSION }}"
          title: "Update schemas to version ${{ env.SCHEMAS_VERSION }}"
          body: |
            This is an auto-generated PR.
            Schemas release: https://github.com/ONSdigital/eq-questionnaire-schemas/releases/tag/${{ env.SCHEMAS_VERSION }}
          branch: "schemas-release-${{ env.SCHEMAS_VERSION }}"
